import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  decideStatus,
  extractCseId,
  footerAllowed,
  guessBridgeSessionId,
  isBotShaped,
  looksLikeUnfilledTemplate,
  normalizeLogin,
  printFooter,
  rcFragment,
  readDeclared,
  readDeclaredHost,
  sessionFragment
} from "../src/identity.mjs";

test("normalizeLogin strips a bot suffix, an app prefix, or neither", () => {
  assert.equal(normalizeLogin("example-agent[bot]"), "example-agent");
  assert.equal(normalizeLogin("app/example-agent-two"), "example-agent-two");
  assert.equal(normalizeLogin("example-user"), "example-user");
  assert.equal(normalizeLogin(""), "");
});

test("isBotShaped recognizes a bot suffix or a leading app/ prefix only", () => {
  assert.equal(isBotShaped("example-agent[bot]"), true);
  assert.equal(isBotShaped("app/example-agent-two"), true);
  assert.equal(isBotShaped("example-user"), false);
  assert.equal(isBotShaped("foo/app/bar"), false);
});

test("decideStatus fails closed on a non-bot-shaped login unless opted in as kind: human", () => {
  assert.equal(decideStatus("example-agent[bot]", "", ""), 0);
  assert.equal(decideStatus("example-agent[bot]", "example-agent", ""), 0);
  assert.equal(decideStatus("example-agent[bot]", "example-agent-two", ""), 1);
  assert.equal(decideStatus("app/example-agent-two", "example-agent-two", ""), 0);
  assert.equal(decideStatus("example-user", "", ""), 2);
  assert.equal(decideStatus("example-user", "example-user", "human"), 0);
  assert.equal(decideStatus("example-user", "someoneelse", "human"), 2);
  assert.equal(decideStatus("", "", ""), 2);
});

test("footerAllowed suppresses the footer for any non-OK status or a kind: human declaration", () => {
  assert.equal(footerAllowed(0, ""), 1);
  assert.equal(footerAllowed(0, "human"), 0);
  assert.equal(footerAllowed(1, ""), 0);
  assert.equal(footerAllowed(2, ""), 0);
});

test("sessionFragment renders only when CLAUDE_CODE_SESSION_ID is set", () => {
  assert.equal(sessionFragment({ CLAUDE_CODE_SESSION_ID: "abc-123" }), "<br>\nSession ID: `abc-123`");
  assert.equal(sessionFragment({}), "");
});

test("extractCseId pulls the id out of a worktree branch or directory shape", () => {
  assert.equal(extractCseId("worktree-bridge-cse_01B7sPkkAYoLP5RFCqD7KNFC"), "01B7sPkkAYoLP5RFCqD7KNFC");
  assert.equal(extractCseId("bridge-cse_abc123"), "abc123");
  assert.equal(extractCseId("main"), null);
});

test("guessBridgeSessionId prefers the branch, falls back to the working directory", () => {
  assert.equal(guessBridgeSessionId("worktree-bridge-cse_ABC", "/irrelevant"), "ABC");
  assert.equal(guessBridgeSessionId("", "/home/x/.claude/worktrees/bridge-cse_ABC123"), "ABC123");
  assert.equal(guessBridgeSessionId("main", "/home/x/plainrepo"), null);
});

test("rcFragment: a confirmed RC id wins over any bridged-signal guess", () => {
  assert.equal(
    rcFragment({ CLAUDE_CODE_BRIDGE_SESSION_ID: "session_abc" }, {}),
    "<br>\nRC: https://claude.ai/code/session_abc"
  );
});

test("rcFragment: no bridge signal at all renders nothing", () => {
  assert.equal(rcFragment({}, {}), "");
});

test("rcFragment: a bridged signal with a guessable worktree name is marked guessed/unverified", () => {
  assert.equal(
    rcFragment(
      { CLAUDE_CODE_CHILD_SESSION: "1" },
      { branch: "", pwd: "/home/x/.claude/worktrees/bridge-cse_ABC123" }
    ),
    "<br>\nRC (**guessed**, **unverified**): https://claude.ai/code/session_ABC123"
  );
});

test("rcFragment: a bridged signal with no guessable name says so plainly", () => {
  assert.equal(
    rcFragment({ CLAUDE_CODE_CHILD_SESSION: "1" }, { branch: "", pwd: "/home/x/plainrepo" }),
    "<br>\nRC: bridged session, no URL available"
  );
});

test("printFooter renders the session id and RC fragments in order, and omits the host clause when blank", () => {
  const state = { declaredName: "", derived: "Example Agent", runtime: "Claude Code", host: "example-host" };

  assert.equal(
    printFooter(state, {}, {}),
    "\n\n***\n\n_Generated by Example Agent via Claude Code on `example-host`._\n"
  );
  assert.equal(
    printFooter(state, { CLAUDE_CODE_SESSION_ID: "abc-123" }, {}),
    "\n\n***\n\n_Generated by Example Agent via Claude Code on `example-host`.<br>\nSession ID: `abc-123`_\n"
  );
  assert.equal(
    printFooter(state, { CLAUDE_CODE_SESSION_ID: "abc-123", CLAUDE_CODE_BRIDGE_SESSION_ID: "session_abc" }, {}),
    "\n\n***\n\n_Generated by Example Agent via Claude Code on `example-host`.<br>\nSession ID: `abc-123`<br>\nRC: https://claude.ai/code/session_abc_\n"
  );
  assert.equal(
    printFooter({ ...state, host: "" }, {}, {}),
    "\n\n***\n\n_Generated by Example Agent via Claude Code._\n"
  );
});

test("readDeclaredHost distinguishes no host: line from a present-but-empty one", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "identity-test-"));
  const file = path.join(dir, "fixture");

  fs.writeFileSync(file, "display_name: Example Agent\napp: example-agent\n");
  assert.deepEqual(readDeclaredHost(file), { declared: false, value: "" });

  fs.appendFileSync(file, "host: example\n");
  assert.deepEqual(readDeclaredHost(file), { declared: true, value: "example" });

  fs.writeFileSync(file, "display_name: Example Agent\nhost:\n");
  assert.deepEqual(readDeclaredHost(file), { declared: true, value: "" });

  fs.rmSync(dir, { recursive: true, force: true });
});

test("readDeclared returns the empty string for a missing key or an unreadable file", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "identity-test-"));
  const file = path.join(dir, "fixture");

  fs.writeFileSync(file, "display_name: Example Agent\n");
  assert.equal(readDeclared("app", file), "");
  assert.equal(readDeclared("display_name", file), "Example Agent");
  assert.equal(readDeclared("app", path.join(dir, "does-not-exist")), "");

  fs.rmSync(dir, { recursive: true, force: true });
});

test("looksLikeUnfilledTemplate flags an unreplaced <placeholder>", () => {
  assert.equal(looksLikeUnfilledTemplate("<your GitHub login>"), true);
  assert.equal(looksLikeUnfilledTemplate("example-agent"), false);
});
